### ISSUE TITLE
[Week 2] The Assembly

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#21]
Attention: read all this document, from start to finish, and ask me any questions before starting.

### Tasks

- [ ] Create a fork of this repo
- [ ] Clone your fork to your local dev environment
- [ ] Install the dependencies and run the `npm run dev` command without issues
- [ ] Confirm access to the design Figma file
- [ ] Review the implementation approach with Lead Developer
- [ ] Review the `kitchen-sink.twig` and the [Content Model](https://github.com/dative/mmisi-frontend/blob/main/CONTENT_MODEL.md) files
- [ ] Assemble the following pages from the design Figma file
  - [ ] Who We Are
  - [ ] Services
  - [ ] Careers

Depending on your progress assembling the pages, we will move in to form elements and video modals, with a focus on accessibility.
  
### Discussion to follow

This second week is about assembling pages with existing components, followinf the  [Content Model](https://github.com/dative/mmisi-frontend/blob/main/CONTENT_MODEL.md). Trainees should NOT:

- Change configurations
- Create or change existing components.

### Deliverables

By the end of the week, you should have a `who-we-are.twig`, `services.twig`, and `careers.twig` pages, that extends the `page.twig`.
You will use random [unsplash.it](https://unsplash.it) for images. Again, you should refer to the `kitchen-sink.twig` page and try to assemble the pages following the same model and style.

The point of this week is to try to emulate other people's code AND style of code.

### Bonus

- [ ] Assemble the `blog.twig` and `blog-detail.twig` pages. For those, you will have to create the following custom components:
  - [ ] `_blog_card.twig` partial with `{ coverPicture, postDate, title }` properties, to be used on the `blog.twig` page.
  - [ ] `_blog_page_header.twig` partial with `{ coverPicture, postDate, title, tags }` properties, to be used on the `blog-detail.twig` page. The `tags` property should be an array of strings.

**Comment by webrgp** [comment]
@jozemaria, @NovaDrake76, @diegocosta-dev

**Comment by jozemaria** [comment]
As soon as I have some time, I will comment on a doubt I had in the development of the project.

**Comment by jozemaria** [comment]
Vou escrever em português para tentar ficar mais explicado.

1- Quando criei uma nova página dentro do diretório ```/template``` e extendi ela para a página ```page.twig``` ela não me retornou a mensagem de erro que estava no else da página, e renderizou um outro componente que estava dentro do diretório, como mostro na imagem abaixo:
![image](https://user-images.githubusercontent.com/29362845/168708645-d066c849-acd2-4134-a3bb-5b2a4b6a116b.png)



2- E outra coisa que não entendi muito bem foi esse ```defined``` e o ``` | raw ```  dentro das condições, eles são palavras reservadas da linguagem?? 
![image](https://user-images.githubusercontent.com/29362845/168709007-8c164454-fb98-4be7-8017-a13da3677406.png)
_Mas já adiantando, vou dar uma lida na documentação..._

Quem poder ajudar também fico agradecido. 

Thanks.

**Comment by webrgp** [comment]
1) Dentro to context to Twig, uma vez que você define uma variável, ela fica disponível a todos os templates naquele contexto, até você reiniciar o build tool. Como o build tool indexes os arquivos twig em ordem alfabética, `test.twig` renders a ultima instancia do `entry`, que é a `services.twig` page.

2) [`defined`](https://twig.symfony.com/doc/3.x/tests/defined.html) e [`raw`](https://twig.symfony.com/doc/3.x/filters/raw.html) docs.

`define` verifica se a variavel foi declarada, `raw` é um filtro que garante que a variavel não irá tentar converter o HTML para text.

**Comment by jozemaria** [comment]
Thanks.
